# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://seoulrental.github.io
title: (주)서울렌탈
email: hansung.seoulrental@gmail.com
author: hansung.dev
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2020 (주)서울렌탈. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'
credits: '업체명: (주)서울렌탈</br>사업자번호: 130-81-62271, 대표자명: 복민서</br>주소: 경기도 화성시 장안면 장안로 309면 장안로 309번 가길 23 (16336)</br>연락처: 031-292-2007, 핸드폰: 010-9034-7575'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap
  - title: <B>렌탈하기</B>
    url: tel:010 9034 7575
#  - title: 문자보내기
#    url: sms:010 9034 7575
